---
title: "GSI correlation heatmap developmental data"
author: "Fabio Sacher"
date: "28.02.2023"
output:
  html_document:
    toc: TRUE
    toc_float: TRUE
    df_print: paged
  html_notebook:
    fig_height: 7
    fig_width: 8
editor_options:
  chunk_output_type: inline
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(
  comment = '', fig.width = 10, fig.height = 7
)
```

```{r libraries, warning = FALSE, message = FALSE, echo = T, results = 'hide'}
library(Seurat)
library(stringr)
library(tibble)
library(dplyr)
library(ggplot2)
library(pheatmap)
library(gridExtra)
```

```{r data-sets}
se_path <- c("Gg_D05_ctrl_seurat_070323",
             "Gg_D07_ctrl_seurat_070323",
             "Gg_ctrl_1_seurat_070323")

clust_col <- read.csv("~/spinal_cord_paper/annotations/broad_cluster_marker_colors.csv") %>% 
  rename(broad = broad_cluster) %>% 
  select(-marker)

```

# pseudobulk matrices

We calulate pseudobulk matrices and normalize them with the gene specificity index, i.e. the average expression of a gene within a cluster (the pseudobulk value) divided by the average expression across all

```{r calculate-gsi-tables}
sct_var <- list()
pb_gsi <- list()
col_table <-list()

for (i in seq(se_path)) {
  # load the data sets
  my.se <- readRDS(paste0("~/spinal_cord_paper/data/", se_path[i], ".rds"))
  annot <- read.csv(list.files("~/spinal_cord_paper/annotations",
                               pattern = str_remove(se_path[i], "_seurat_\\d{6}"),
                               full.names = TRUE))
  
  if(length(table(annot$number)) != length(table(my.se$seurat_clusters))) {
     stop("Number of clusters must be identical!")
  }
  
  # rename for left join
  annot <- annot %>% 
    mutate(fine = paste(fine, number, sep = "_")) %>% 
    mutate(number = factor(number, levels = 1:nrow(annot))) %>% 
    rename(seurat_clusters = number) 
  
  # create index for color coding
  col_table[[i]] <- annot %>%
    left_join(clust_col, by = "broad") %>% 
    select(c("fine", "color"))
  
  # add cluster annotation to meta data
  my.se@meta.data <- my.se@meta.data %>% 
    rownames_to_column("rowname") %>% 
    left_join(annot, by = "seurat_clusters") %>% 
    column_to_rownames("rowname")
  
  Idents(my.se) <- "fine" 
  # var features
  sct_var[[i]] <- my.se[["SCT"]]@var.features 
  # calculate pseudobulk
  pseu_bulk <- as.matrix(AverageExpression(
    my.se,
    assays = "SCT",
    slot = "data")[[1]])
  
  # individual gsi matrices
  pb_gsi[[i]] <- pseu_bulk/rowMeans(pseu_bulk)

}

names(sct_var) <- c("D05", "D07", "D10")
names(pb_gsi) <- c("D05", "D07", "D10")
names(col_table) <- c("D05", "D07", "D10")

rm(my.se, annot, pseu_bulk)
```

```{r filter-for-sct-var-gene-universe}
univ <- Reduce(intersect, sct_var)

matrix_filt <- function(x, features) {
  filt <- x[features,]
  return(filt)
}

pb_gsi_univ <- lapply(pb_gsi, matrix_filt, features = univ)

rm(pb_gsi)

#set colnames
for (i in seq(pb_gsi_univ)) {
  colnames(pb_gsi_univ[[i]]) <- paste0(names(pb_gsi_univ)[[i]], "_", colnames(pb_gsi_univ[[i]]))
}

```


```{r combine}
if(!all(identical(rownames(pb_gsi_univ[["D05"]]),
              rownames(pb_gsi_univ[["D07"]])),
    identical(rownames(pb_gsi_univ[["D07"]]),
              rownames(pb_gsi_univ[["D10"]])))) {
  stop("Rownames are not identical!")
}

pb_gsi_univ <- do.call(cbind, pb_gsi_univ)
dim(pb_gsi_univ)
```
# Heatmap

## annotations

```{r annot-list}

# names and colors for the heatmap annotation
annot_name <- data.frame(
  "Celltypes" = colnames(pb_gsi_univ),
  "Sample"    = substr(colnames(pb_gsi_univ),1,3),
  row.names = colnames(pb_gsi_univ)
  )

col_table <- do.call(rbind, col_table) %>% 
  rownames_to_column("sample") %>% 
  mutate(sample = substr(sample, 1,3)) %>% 
  mutate(fine = paste(sample, fine, sep = "_"))

# match color table with annotation
col_table <- col_table[match(annot_name$Celltypes, col_table$fine),]

annot_col <- list(
  Celltypes = col_table$color,
  Sample = c(D05 = "#A4A4A4",
             D07 = "#515151",
             D10 = "#000000")
  )

names(annot_col[[1]]) <- annot_name$Celltypes

```

## Correlation of GSI pseudobulk expression (over ind. samples)

GSI over individual samples (before cbind)

```{r ind-gsi-heatmap, fig.height=11, fig.width=12}

heat_col <- colorRampPalette(colors = c("dodgerblue4","dodgerblue", "white", "red", "darkred"))

tmp <- cor(pb_gsi_univ, method = "spearman")

# lower limit to scale color bar
low_limit <- 100 - abs(round(range(tmp)[1]*100))

corr_heatmap <- pheatmap(tmp,revC = T,
                 main = "D5_ctrl, D7, and D10 ctrl_1 GSI pseudobulk spearman corr\n(intersection of SCT variable features)\nGSI claculation before cbind",
                 fontsize = 8,  
                 color = heat_col(200)[low_limit:200],
                 show_colnames = F, 
                 treeheight_row = 0, 
                 annotation_col = annot_name,
                 annotation_colors = annot_col,
                 annotation_legend = F,
                 border_color = NA
                 )
```

```{r export}
pdf("~/spinal_cord_paper/figures/heatmap_spearman_devel.pdf", width = 12, height = 11)
grid.arrange(corr_heatmap[[4]])
dev.off()
```


```{r}
# Date and time of Rendering
Sys.time()

sessionInfo()
```