---
title: "Integration of Gg lumb 1 and 2"
author: "Fabio Sacher"
date: "06.02.2023"
output:
  html_document:
    toc: TRUE
    toc_float: TRUE
    df_print: paged
  html_notebook:
    fig_height: 7
    fig_width: 8
editor_options:
  chunk_output_type: inline
---

Render this script with > sbatch ~/spinal_cord_paper/scripts/Seurat_integration_array.sh

```{r, setup, include=FALSE}
knitr::opts_chunk$set(
  comment = '', fig.width = 10, fig.height = 7
)
```

```{r libraries, warning = FALSE, message = FALSE, echo = T, results = 'hide'}
library(Seurat)
library(magrittr)
```

```{r, load data}
my.samples <- list()

my.samples[[1]] <- readRDS("~/spinal_cord_paper/data/Gg_lumb_1_seurat_070223.rds")
my.samples[[2]] <- readRDS("~/spinal_cord_paper/data/Gg_lumb_2_seurat_070223.rds")

names(my.samples) <- c("Gg_lumb_1", "Gg_lumb_2")

```

```{r, Integration step}
# integration features
features <- SelectIntegrationFeatures(
	object.list = my.samples,
	nfeatures = 3000
	)

# prepare integration 
my.samples <- PrepSCTIntegration(
	object.list = my.samples,
	anchor.features = features
	)

# find anchors
NT.anchors <- FindIntegrationAnchors(
	object.list = my.samples,
	normalization.method = "SCT",
	anchor.features = features
	)

rm(my.samples)

# integrate
int.nt.sct <- IntegrateData(
	anchorset = NT.anchors,
	# features.to.integrate = all_features,
	normalization.method = "SCT"
	)

# compute PCA
int.nt.sct <- RunPCA(
	int.nt.sct,
	verbose = FALSE
	)

# Run UMAP
int.nt.sct <- RunUMAP(
	int.nt.sct,
	reduction = "pca",
	dims = 1:30
	)

```

## inspect the data

```{r, inspection}

PCAPlot(int.nt.sct)

DimPlot(int.nt.sct, reduction = "umap")

```

## save the integrated object

```{r, save object}
saveRDS(int.nt.sct, file = paste0("~/spinal_cord_paper/data/Gg_lumb_integrated_",format(Sys.Date(), "%d%m%y"),".rds"))
```

```{r sessionInfo}
# Date and time of Rendering
Sys.time()

sessionInfo()
```

