---
title: "MT and RB percent vln plots"
author: "Fabio Sacher"
date: "07.08.2023"
output:
  html_document:
    toc: TRUE
    toc_float: TRUE
    df_print: paged
  html_notebook:
    fig_height: 7
    fig_width: 8
editor_options:
  chunk_output_type: inline
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(
  comment = '', fig.width = 10, fig.height = 7
)
```

```{r libraries, warning = FALSE, message = FALSE, echo = T, results = 'hide'}
library(Seurat)
library(stringr)
library(tibble)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(patchwork)
library(modplots)
```

# Diagnostig violin plots

Those plots serve to quickly reference MT (mitochondrial) and RB (ribosomal) gene expression percentages per cluster.

Render with ./scripts/Vln_plots_render.sh.

```{r seurat-objects}
se_path <- c("Gg_D05_ctrl_seurat_070323",
             "Gg_D07_ctrl_seurat_070323",
             "Gg_ctrl_1_seurat_070323",
             "Gg_ctrl_int_seurat_250723",
             "Gg_lumb_int_seurat_250723",
             "Gg_poly_int_seurat_250723",
             "Gg_ctrl_lumb_int_seurat_250723",
             "Gg_ctrl_poly_int_seurat_250723")
```

```{r order}

broad_order <- c("progenitors",
      "FP",
      "RP",
      "FP/RP",
      "neurons",
      "OPC",
      "MFOL",
      "pericytes",
      "microglia",
      "blood",
      "vasculature"
      )

```


```{r}
clust_col <- read.csv("~/spinal_cord_paper/annotations/broad_cluster_marker_colors.csv") %>% 
  rename(broad = broad_cluster) %>% 
  select(-marker)

mt <- list()
rb <- list()
label <- list()

for (i in seq(se_path)) {
  # load the data sets
  my.se <- readRDS(paste0("~/spinal_cord_paper/data/", se_path[i], ".rds"))
  annot <- read.csv(list.files("~/spinal_cord_paper/annotations",
                               pattern = str_remove(se_path[i], "_seurat_\\d{6}"),
                               full.names = TRUE))
  
  if(length(table(annot$number)) != length(table(my.se$seurat_clusters))) {
     stop("Number of clusters must be identical!")
  }
  
  # rename for left join
  annot <- annot %>% 
    mutate(fine = paste(fine, number, sep = "_")) %>% 
    mutate(number = factor(number, levels = 1:nrow(annot))) %>% 
    rename(seurat_clusters = number)
  
  ord_levels <- annot$fine[order(match(annot$broad, broad_order))]
   
  # add cluster annotation to meta data
  my.se@meta.data <- my.se@meta.data %>% 
    rownames_to_column("rowname") %>% 
    left_join(annot, by = "seurat_clusters") %>% 
    mutate(fine = factor(fine, levels = ord_levels)) %>% 
    column_to_rownames("rowname")
  
  col_table <- annot %>%
    left_join(clust_col, by = "broad") %>% 
    select(c("fine", "color"))
  
  
  # without x labs so plots have the same height
  mt[[i]] <- VlnPlot(my.se,
    group.by = "fine",
    features = "percent.mt",
    fill.by = "ident",
    y.max = 60,
    cols = col_table$color[as.integer(str_extract(ord_levels, "\\d{1,2}$"))]) +
  ggtitle(paste0(my.se@project.name, " MT % VlnPlot")) + 
  theme(axis.text.x = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
    NoLegend()
  
  rb[[i]] <- VlnPlot(my.se,
    group.by = "fine",
    features = "percent.rb",
    fill.by = "ident",
    y.max = 50,
    cols = col_table$color[as.integer(str_extract(ord_levels, "\\d{1,2}$"))]) +
  ggtitle(paste0(my.se@project.name, " RB % VlnPlot")) + 
  theme(axis.text.x = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
    NoLegend()
  
  label[[i]] <- VlnPlot(my.se,
    group.by = "fine",
    features = "percent.rb",
    fill.by = "ident",
    cols = col_table$color[as.integer(str_extract(ord_levels, "\\d{1,2}$"))]) +
  ggtitle(paste0(my.se@project.name, " VlnPlot label")) + 
    ylim(c(0,0)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5),
        plot.title = element_text(hjust = 0.5)) +
    NoLegend()
  
}

rm(my.se)

names(mt) <- str_remove_all(se_path, "_seurat_\\d{6}")
names(rb) <- str_remove_all(se_path, "_seurat_\\d{6}")
names(label) <- str_remove_all(se_path, "_seurat_\\d{6}")

```

```{r warning=FALSE}
pdf("~/spinal_cord_paper/figures/test_vln_plots.pdf", width = 7, height = 5)

for (i in seq(se_path)) {
  print(mt[[i]])
  print(rb[[i]])
  print(label[[i]])
}


```


```{r}
# Date and time of Rendering
Sys.time()

sessionInfo()
```