Rscript -e rmarkdown::render('~/spinal_cord_paper/markdown/QCfilter_ctrl1.Rmd')
Rscript -e rmarkdown::render('~/spinal_cord_paper/markdown/QCfilter_ctrl2.Rmd')
Rscript -e rmarkdown::render('~/spinal_cord_paper/markdown/QCfilter_lumb1.Rmd')
Rscript -e rmarkdown::render('~/spinal_cord_paper/markdown/QCfilter_lumb2.Rmd')
Rscript -e rmarkdown::render('~/spinal_cord_paper/markdown/QCfilter_poly1.Rmd')
Rscript -e rmarkdown::render('~/spinal_cord_paper/markdown/QCfilter_poly2.Rmd')
Rscript -e rmarkdown::render('~/spinal_cord_paper/markdown/QCfilter_D5_ctrl.Rmd')
Rscript -e rmarkdown::render('~/spinal_cord_paper/markdown/QCfilter_D7_ctrl.Rmd')